### ISSUE TITLE
Ethics for Design

### ISSUE THREAD

**Issue by afivos** [sarahfossheim/ethicaldesign.guide#1]
[Ethics for Design](https://ethicsfordesign.com) is a 50-minute interactive documentary that questions the designer’s ethics. It is free, open-source and under Creative Commons.

By Gauthier Roussilhe.

**Comment by sarahfossheim** [comment]
Thanks for suggesting ✨ Just watched it in full! 

Added here: https://github.com/sarahfossheim/ethicaldesign.guide/commit/518deab0c12bc651aa00be46dded57cda7fc475a
