### ISSUE TITLE
[bug] Topic buttons with multiple words split when hovered over

### ISSUE THREAD

**Issue by alex-bellon** [sarahfossheim/ethicaldesign.guide#4]
On the home page, when you hover over a topic button that has more than one word, it will split the button in half into multiple lines:

![image](https://user-images.githubusercontent.com/24237402/108897338-9a2f2280-75db-11eb-896d-4c0509b51691.png)

Using `Mozilla Firefox 84.0.2`, and this issue appears on all window sizes.

**Comment by Ryuno-Ki** [comment]
Interesting! I inspected and played around and can see, that `margin-right: -4px` is causing this.

**Comment by sarahfossheim** [comment]
Thanks for flagging 😊 Was indeed an issue with the margins in Firefox, fixed here: https://github.com/sarahfossheim/ethicaldesign.guide/commit/dd85eb6a886266d4cb48bedc7dc5ed0bc8fd4f4d.
