### ISSUE TITLE
[resource] ACM code of ethics and professional conduct

### ISSUE THREAD

**Issue by cthierry** [sarahfossheim/ethicaldesign.guide#5]
https://www.acm.org/code-of-ethics

The ACM published this inspiring code of ethics and professional conduct for computing professionals. I think it is definitively relevant for designers.

**Comment by sarahfossheim** [comment]
Added: https://github.com/sarahfossheim/ethicaldesign.guide/commit/056af01ea1d5dbd771ccb575c85c49c952a2b3cd.

**Comment by sarahfossheim** [comment]
Thanks for submitting! ⭐️
